version: 2

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
    - bash scripts/completions.sh
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s
      - -w
      - -X github.com/s-matsubara/git-auto/cmd.Version={{ .Version }}
      - -X github.com/s-matsubara/git-auto/cmd.Commit={{ .ShortCommit }}
      - -X github.com/s-matsubara/git-auto/cmd.BuildDate={{ .Date }}
archives:
  - format: tar.gz
    files:
      - completions/*

universal_binaries:
  - replace: true

homebrew_casks:
  - completions:
      bash: completions/git-auto.bash
      zsh: completions/git-auto.zsh
      fish: completions/git-auto.fish
    repository:
      owner: s-matsubara
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    caveats: |
      If you want to register for git alias:
      
        git config --global alias.auto '!git-auto'
        git config --global alias.mergedd '!git-auto delete-merged-branch'
        git config --global alias.auto-tag '!git-auto tag'

      To see how to use:
      
        git-auto -h
